version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
      - gradle test
artifacts:
  files:
    - app/build/libs/snakebot-app-*.jar
