version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/openjdk:11

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      
      - restore_cache:
          name: Restore Gradle wrapper
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          name: Restore Gradle caches
          keys: 
            - gradle-caches-{{ checksum "build.gradle" }}-{{ checksum "api/build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "client/build.gradle" }}-{{ checksum "client-util/build.gradle" }}-{{ checksum "domain/build.gradle" }}-{{ checksum "javafxclient/build.gradle" }}
            - gradle-caches-

      - run: 
          name: Download Gradle dependencies
          command: ./gradlew downloadDependencies

      - save_cache:
          name: Save Gradle wrapper
          when: always
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper

      - save_cache:
          name: Save Gradle caches
          when: always
          key: gradle-caches-{{ checksum "build.gradle" }}-{{ checksum "api/build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "client/build.gradle" }}-{{ checksum "client-util/build.gradle" }}-{{ checksum "domain/build.gradle" }}-{{ checksum "javafxclient/build.gradle" }}
          paths:
            - ~/.gradle/caches

      - run: 
          name: Run build without tests
          command: ./gradlew build -x test

workflows:
  version: 2
  build:
    jobs:
      - build
