version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/openjdk:11

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Gradle cache
          key: gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "api/build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "client/build.gradle" }}-{{ checksum "client-util/build.gradle" }}-{{ checksum "domain/build.gradle" }}-{{ checksum "javafxclient/build.gradle" }}
      - run: 
          name: Run Gradle build without tests
          command: ./gradlew build -x test
      - save_cache:
          name: Save Gradle cache
          when: always
          key: gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "api/build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "client/build.gradle" }}-{{ checksum "client-util/build.gradle" }}-{{ checksum "domain/build.gradle" }}-{{ checksum "javafxclient/build.gradle" }}
          paths:
            - ~/.gradle
      - persist_to_workspace:
          root: ~/code
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/code
      - run: 
          name: Run Gradle tests
          command: ./gradlew test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires: 
            - build
