# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/openjdk:11

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test
     
workflows:
  version: 2
  test:
    jobs:
      - test